### ISSUE TITLE
tab-content component is missing route prop documentation.

### ISSUE THREAD

**Issue by SamRahnama** [parsajiravand/vue3-form-wizard#15]
hi there 
I have noticed that the documentation for the tab-content props is missing **route** prop for the Vue component.
best regards

**Comment by parsajiravand** [comment]
Hello my friend, I hope doing well.
Thanks a lot for your suggest I will update documention in the next version.

If you wanna help about this you can create code sand boxes with router option and sample after we can share your code in documention (samples and playground)

@SamRahnama

**Comment by parsajiravand** [comment]
### Update Documention

- [X] Update Documention with route option  (TabContent) 
- [X] Code sanbox 

https://vue3-form-wizard-document.netlify.app/props/#tab-content-props
https://vue3-form-wizard-document.netlify.app/playground/#sample-vue3-form-wizard-router-option
