### ISSUE TITLE
v-if only hiding tab content not whole tab second time,

### ISSUE THREAD

**Issue by roshanlal-promenna** [parsajiravand/vue3-form-wizard#16]
I'm showing tabs conditionally. First time variable is true and based on http request I'm changing variable to false at that time only tab content is not showing, but fully tab is not hiding.

**Comment by parsajiravand** [comment]
Thanks for comment

Can you share code or sample with us?

@roshanlal-promenna

**Comment by roshanlal-promenna** [comment]
`
<form-wizard @on-complete="onComplete"
        color="#428bca"
        error-color="#a94442"
        transition="fade"
        mode="out-in"
>

      <tab-content 
           v-if="showInstrumentTab"
            title="General Question"                
            icon="fa fa-address-card"
            :before-change="validateFirstTab"
        >
    
     </tab-content>
</form-wizard>
METHODS PART

async validateFirstTab() {
                
                const vm = this;
                if (!vm.model.Phone) {
                    vm.model.phoneisvalid = false;
                }

                const isFormValid = await vm.$refs.firstTabForm.validate();

                if (isFormValid.valid && vm.model.phoneisvalid) {
                    vm.checkApplicant();
                }

                // vm.$refs.firstTabForm.submit();
                
                return isFormValid.valid && vm.model.phoneisvalid;
            },
async checkApplicant() {
                const vm = this;

                const response = await vm.$http.post('/musical/public/check-musician-exist', {
                    email : vm.model.email,
                    phone: vm.model.Phone
                });

                if(response.data.status){
                    vm.model.applicantexist = true;
                    vm.applicantexistchecked = true;
                } else {
                    vm.model.applicantexist = false;
                }
            },
computed: {
           showInstrumentTab() {
                return !this.model.applicantexist;
            },
        },
`

**Comment by parsajiravand** [comment]
Thanks i hope understand your issue well, you can handel this with refrence ($ref)
Unfortuanaly if you wanna remove your  tab, you need to re-render FormWizard component becuase new tab added to last index

**I will working on this new feautre on new release (adding hide option for tab)**

``` vue
<script lang="ts">
import { defineComponent } from "@vue/runtime-core";
import { FormWizard, TabContent } from "vue3-form-wizard";
import 'vue3-form-wizard/dist/style.css'

export default defineComponent({
  components: {
    FormWizard,
    TabContent,
  },
  data() {
    return {
      showTab: true,
      randomKey: 0,
    };
  },

  methods: {
    onComplete() {
      alert("Yay. Done!");
    },

    toggleTab() {
      this.showTab = !this.showTab;
      // random key between 1 too 1000
      this.randomKey = Math.floor(Math.random() * 1000) + 1;
      this.$refs.wizard.removeTab(this.$refs.wizardTabShouldHide);
    },
  },
});
</script>

<template>
  <button @click="toggleTab">toggle tab</button>
  <form-wizard
    @on-complete="onComplete"
    :key="randomKey"
    color="#9b59b6"
    ref="wizard"
  >
    <tab-content title="Personal details" icon="fa fa-user">
      My first tab content
    </tab-content>
    <tab-content title="Additional Info"> My second tab content </tab-content>

    <tab-content
      v-if="showTab"
      title="before last step"
      icon="fa fa-heart"
      ref="wizardTabShouldHide"
    >
      This Tab should be hidden
    </tab-content>

    <tab-content title="Last step" icon="fa fa-check">
      Yuhuuu! This seems pretty damn simple
    </tab-content>
  </form-wizard>
</template>

<style>
@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css");
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

```
@roshanlal-promenna

**Comment by roshanlal-promenna** [comment]
@parsajiravand Yes now its able to remove the tab. But If Im hiding second tab and after hiding its always going to first tab. It should goto 3 tab automatically.

**Comment by parsajiravand** [comment]
Okay you can handel this with changeTab function.

``` js
toggleTab() {
      this.showTab = !this.showTab;
      // random key between 1 too 1000
      this.randomKey = Math.floor(Math.random() * 1000) + 1;
      this.$refs.wizard.removeTab(this.$refs.wizardTabShouldHide);
      this.$nextTick(() => {
        const activeIndex = 2;
        this.$refs.wizard.changeTab(0, activeIndex);;
        this.$refs.wizard.tabs.forEach((element, index) => {
          // before activeIndex set all tabs checked to true
          if (index < activeIndex) {
            element.checked = true;
          }
        });
      });
    },

 ```
 
 @roshanlal-promenna

**Comment by roshanlal-promenna** [comment]
@parsajiravand Working. Thanks a lot for your help !
