### ISSUE TITLE
Validate form in tabs

### ISSUE THREAD

**Issue by fabioselau077** [parsajiravand/vue3-form-wizard#19]
I have a wizard that will have some forms inside it.
I was thinking about using @on-change="onChange" to validate, however this function is triggered after changing the tab.
What would make the most sense would be before-change, because according to validation it could return true or false, but in this Tab event I don't have the index of the clicked tab

**Comment by parsajiravand** [comment]
Hello my friend if you expain more about your problem i will be great.
If  i understand well you want access index instance for your validation.
Please you check this part of documents after that ping me tnx.
https://vue3-form-wizard-document.netlify.app/events/#events
https://jsfiddle.net/bt5dhqtf/272/
@fabioselau077

**Comment by parsajiravand** [comment]
Hi my friend,
your issue are solved or not?
@fabioselau077
