### ISSUE TITLE
Adding Custom Classes

### ISSUE THREAD

**Issue by LRJasmine** [parsajiravand/vue3-form-wizard#20]
Is there a way to add custom  classes to the wizard and each tab?
Currently I am aiming to target .vue-form-wizard .wizard-icon-circle.tab_shape.checked 
However the add custom classes has not been fruitful as the class is added but the styles for that class doesn't show.

**Comment by parsajiravand** [comment]
You can customize form wizard without problem if having some issue please share your code i will check.
@LRJasmine
