### ISSUE TITLE
The line to the left of the sphere

### ISSUE THREAD

**Issue by LRJasmine** [parsajiravand/vue3-form-wizard#21]
How can I move the line to the left of the sphere to start at the first sphere instead of before it?

**Comment by LRJasmine** [comment]
This works when I tried to make the edits in the console.
I am using Vuejs and laravel.

.wizard-progress-with-circle { 
    left: 100px !important; 
}
This works in the component style tag but not with scoped

.wizard-progress-bar {
    width: 80% !important;
}
This is not causing a change in the vue file at all.

Put both of those in a scss file and not changing either

**Comment by parsajiravand** [comment]
you can set your custom class **out side of the scoped css** in vue like this:
```vue
.custom-form-wizard{
   .wizard-progress-with-circle {
    left: 100px !important;
   }
  .wizard-progress-bar {
   width: 80% !important;
  }
}
 ```

**Comment by parsajiravand** [comment]
you can write your dynamic style calc like this:
calc($size/2) + 5px;

**Comment by parsajiravand** [comment]
Hi my friend,
your issue are solved or not? 
@LRJasmine
