### ISSUE TITLE
scoped slot syntax is wrong

### ISSUE THREAD

**Issue by vesper8** [parsajiravand/vue3-form-wizard#9]
Hello!

First of, thanks a lot for porting this package to Vue 3! I've been using it for years with Vue 2 and am happy to be able to pull it into a new Vue 3 project now thanks to your efforts.

I tried migrating my customized wizard and quickly found that the scope slot syntax throws an error.

In Vue 2 you would do this:

```

<template slot="footer" slot-scope="props">
```

but in Vue 3 you must do this:

```

<template v-slot:footer="props">
```

And voila, like this it works.

Same for the step slot:

```
<template v-slot:step="props">
```

Cheers!

**Comment by parsajiravand** [comment]
Hi my new friend thanks for having my back

**scoped slot structores changed in vue3 but i forgotten update this in new document, thanks a lot for your help.**
@vesper8

**Comment by parsajiravand** [comment]
**update scoped-slots in documention and create demo**

https://vue3-form-wizard-document.netlify.app/scoped-slots/
https://vue3-form-wizard-document.netlify.app/demos/#custom-slot-props-footer-step
